### ISSUE TITLE
About the function of ALRT AMC implementation

### ISSUE THREAD

**Issue by Roseblac** [iyytdeed/Automatic-Modulation-Classification#3]

**Comment by Roseblac** [comment]
Hi. I reviewed your MATLAB code and the original paper on the ML-based AMC.

I would like to ask why you ignored the noise variance _N_ in the likelihood function. Although your results are not affected. 

use the function-alrt-psk8 as example:
![image](https://user-images.githubusercontent.com/37896615/100146193-7c66fa00-2ed4-11eb-8fc7-1989723afd07.png)

Thank you very much.

**Comment by iyytdeed** [comment]
Hi Roseblac

noise of signal is contained in r

e.g.
**signal_data(row, col)** = sqrt(P)*h(row, 1)*s + **sqrt(1/2)*(randn+j*randn)**;
...
likelihood_psk8 = func_alrt_psk8(**signal_data(n,:)**, P, h(n,1));
...
val = (1/pi)*exp(-abs(**r** - sqrt(P)*h*x(m))^2);

Regards

**Comment by Roseblac** [comment]
Thank you. Btw, your code helps me a lot. :) 

吐槽：调制识别的文章复现太鬼畜了,我要吐了。
